# which directories should be walked to find git repositories?
scandirs:

  # a list of one/more starting points
  # this will have env vars expanded
  include:
    - $HOME/apps
    - $HOME/c*

  # a list of specific directories to exclude from the scan this will have env
  # vars expanded
  #
  # when path does not start with '/' the baseName of the directory will be
  # compared.
  exclude:
    - $GOPATH/pkg
    - .terraform

# which files to ignore inside a git repo any .gitignore file in your repo
# will be adhered to, the config below allows your repo to consider files
# to be added but ignored by dirtygit
gitignore:

  fileglob:
    - .terraform.lock.hcl
    - go.sum
    - log
    - "*.orig"
    - "*.old"
    - "*.rpm"
    - "*.pyc"
    - .DS_Store

  dirglob:
    - vendor
    - new
    - old
    - .terraform

# if true, walking the directory tree underneath the `include` directories
# will traverse directories pointed to be symlinks
followsymlinks: true

edit_command: code %WORKING_DIRECTORY
